services:
    postgres:
        container_name: postgres
        build:
            context: ./postgres
            dockerfile: Dockerfile.dev
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
