FROM alpine:3.18

RUN apk update
RUN apk add --no-cache \
 bash \
 postgresql \
 postgresql-contrib

RUN mkdir -p /usr/local/pgsql/data

RUN chown postgres:postgres /usr/local/pgsql/data

COPY start.sh /start.sh

RUN chown postgres:postgres /start.sh

USER postgres

RUN initdb -D /usr/local/pgsql/data

RUN chmod +x /start.sh

EXPOSE 5432

CMD ["./start.sh"]