FROM alpine:3.18

RUN apk update
RUN apk add --no-cache \
 bash \
 postgresql \
 postgresql-contrib

# Create dir for pgsql
RUN mkdir -p /usr/local/pgsql/data
RUN chown postgres:postgres /usr/local/pgsql/data

RUN mkdir -p /run/postgresql
RUN chown postgres:postgres /run/postgresql

# Custom scripts
RUN mkdir -p /scripts

# Copy the script that starts the Postgres Server
COPY start.sh /scripts/start.sh
RUN chown postgres:postgres /scripts/start.sh
RUN chmod +x /scripts/start.sh

# Copy the script that initializes DB and Table
COPY init.sql /scripts/init.sql
RUN chown postgres:postgres /scripts/init.sql
RUN chmod +x /scripts/init.sql

USER postgres

# Initialize the database
RUN initdb -D /usr/local/pgsql/data

# Expose the port
EXPOSE ${POSTGRES_PORT}

CMD ["./scripts/start.sh"]